language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install

stages:
  - lint
  # - name: gh_pages
  #   if: branch = master

jobs:
  include:
    - stage: lint
      script: npm run lint
    # - stage: gh_pages
    #   script: npm run build:gh-pages
    #   after_script:
    #     - cd ./dist
    #     - git init
    #     - git remote add origin "https://${GH_TOKEN}@${GH_REF}"
    #     - git checkout -b gh-pages
    #     - git config user.name "leezng"
    #     - git config user.email "im.leezng@gmail.com"
    #     - git add .
    #     - git commit -m "update gh-pages"
    #     - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

env:
  global:
    - GH_REF: github.com/leezng/iMusic.git
